// PSKL Assistant backend template for Cloudflare Workers / compatible edge runtimes.
// Required secret: OPENAI_API_KEY. Optional: OPENAI_MODEL (default gpt-5.6-terra).
// Do NOT put the API key in index.html or browser JavaScript.
const SITE_ORIGIN='https://klinowskimichal-maker.github.io';
function cors(origin){const allowed=origin===SITE_ORIGIN||origin==='http://localhost:8000'||origin==='http://127.0.0.1:8000';return {'Access-Control-Allow-Origin':allowed?origin:SITE_ORIGIN,'Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Vary':'Origin'};}
function textFromResponse(data){for(const item of data.output||[]){if(item.type!=='message')continue;for(const part of item.content||[]){if(part.type==='output_text'&&part.text)return part.text;}}return data.output_text||'';}
export default {async fetch(request,env){const origin=request.headers.get('Origin')||SITE_ORIGIN;const headers=cors(origin);if(request.method==='OPTIONS')return new Response(null,{status:204,headers});if(request.method!=='POST')return Response.json({error:'Method not allowed'},{status:405,headers});if(!env.OPENAI_API_KEY)return Response.json({error:'OPENAI_API_KEY is not configured'},{status:503,headers});
 try{const body=await request.json();const message=String(body.message||'').slice(0,4000);const context=body.context&&typeof body.context==='object'?body.context:{};if(!message)return Response.json({error:'Empty message'},{status:400,headers});
 const wantsCurrent=/aktual|dzis|cena|rynek|ofert|warto kup|finn|blocket|olx|allegro|boat24/i.test(message);
 const payload={model:env.OPENAI_MODEL||'gpt-5.6-terra',store:false,reasoning:{effort:'low'},text:{verbosity:'low'},instructions:'Jesteś Pirackim Asystentem PSKŁ — pomocnym, zwięzłym doradcą na stronie Polskiego Stowarzyszenia Klasycznych i Zabytkowych Łodzi. Odpowiadaj po polsku. Specjalizacja: klasyczne drewniane łodzie, konstrukcja, oryginalne silniki, renowacja, wyszukiwanie ofert i wstępna ocena zakupu. Korzystaj z kontekstu strony. Jeśli oceniasz ofertę, oddziel fakty od przypuszczeń, wskaż ryzyka i listę rzeczy do sprawdzenia. Nie przedstawiaj wstępnej oceny jako surveyu technicznego ani profesjonalnej wyceny. Gdy pytanie dotyczy aktualnej ceny, dostępności lub rynku i masz narzędzie wyszukiwania, zweryfikuj informacje w sieci.',input:[{role:'user',content:[{type:'input_text',text:`Pytanie użytkownika:\n${message}\n\nKontekst aktualnej strony PSKŁ:\n${JSON.stringify(context).slice(0,12000)}`}]}]};if(wantsCurrent)payload.tools=[{type:'web_search_preview'}];
 const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data?.error?.message||`OpenAI HTTP ${r.status}`);const answer=textFromResponse(data)||'Nie udało mi się przygotować odpowiedzi.';return Response.json({answer},{headers:{...headers,'Content-Type':'application/json; charset=utf-8'}});
 }catch(err){return Response.json({error:'Assistant request failed',detail:String(err?.message||err)},{status:500,headers});}}
};
